version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - checkout
      - run: 
          name: Win10/Pro/x64/21H2/English
          no_output_timeout: 30m
          command: pwsh -file ./Win10/Pro/x64/21H2/English.ps1
      - run: 
          working_directory: ~/
          name: Run tests
          command: |
            pwd
workflows:
  main-workflow:
    jobs:
      - build