version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  WIN10_Home_21H2:
    executor: win/server-2022
    steps:
      - checkout
      - run: 
          name: Windows10/Home/21H2
          no_output_timeout: 30m
          command: pwsh -file ./Windows10/Home/21H2.ps1
  WIN10_Home_21H1:
    executor: win/server-2022
    steps:
      - checkout
      - run: 
          name: Windows10/Home/21H1
          no_output_timeout: 30m
          command: pwsh -file ./Windows10/Home/21H1.ps1
  
  WIN10_Pro_21H2:
    executor: win/server-2022
    steps:
      - checkout
      - run: 
          name: Windows10/Pro/21H2
          no_output_timeout: 30m
          command: pwsh -file ./Windows10/Pro/21H2.ps1
  WIN10_Pro_21H1:
    executor: win/server-2022
    steps:
      - checkout
      - run: 
          name: Windows10/Pro/21H1
          no_output_timeout: 30m
          command: pwsh -file ./Windows10/Pro/21H1.ps1

workflows:
  Win10_Pro:
    jobs:
      - WIN10_Pro_21H2
      - WIN10_Pro_21H1:
          requires:
            - WIN10_Pro_21H2
  Win10_Home:
    jobs:
      - WIN10_Home_21H2
      - WIN10_Home_21H1:
          requires:
            - WIN10_Home_21H2